# -*- coding: utf-8 -*-
"""Inhalte der zehn Carousel-Posts, zweite Staffel."""

R = '<span style="color: #8C1010;">%s</span>'

POSTS = [
    {
        'key': 'Huefte', 'page': 'Hüfte', 'badge': 'Hüft-Edition', 'hero': 'huefte',
        'aussage': 'Schmerzen in der ' + R % 'Hüfte' + ' zeigen sich oft zuerst bei ganz normalen Alltagsbewegungen:',
        'karten': [('zeit', 'Anlaufschmerz'), ('stufen', 'Treppensteigen'),
                   ('gelenk', 'Schuhe binden'), ('blitz', 'Ausstrahlender Schmerz')],
        'unter': 'bei Hüftbeschwerden:',
        'punkte': ['Beweglichkeit erhalten', 'Hüftmuskulatur kräftigen',
                   'Gangbild verbessern', 'Belastung dosieren'],
        'band': 'Denn: Eine bewegliche Hüfte trägt den ganzen Alltag mit.',
        'frage': 'Zwickt deine Hüfte beim Aufstehen oder Treppensteigen?',
    },
    {
        'key': 'Kiefer', 'page': 'Kiefergelenk', 'badge': 'Kiefer-Edition', 'hero': 'kiefer',
        'aussage': 'Ein überlastetes ' + R % 'Kiefergelenk' + ' macht sich selten nur im Kiefer bemerkbar:',
        'karten': [('gelenk', 'Knacken beim Öffnen'), ('nacht', 'Zähneknirschen'),
                   ('stress', 'Kopfschmerzen'), ('blitz', 'Verspannter Nacken')],
        'unter': 'bei Kiefergelenkbeschwerden:',
        'punkte': ['Kiefergelenk mobilisieren', 'Kaumuskulatur lösen',
                   'Nacken einbeziehen', 'Alltag entlasten'],
        'band': 'Denn: Kiefer, Nacken und Kopf arbeiten immer zusammen.',
        'frage': 'Knackt dein Kiefer oder wachst du verspannt auf?',
    },
    {
        'key': 'Ellenbogen', 'page': 'Ellenbogen', 'badge': 'Ellenbogen-Edition', 'hero': 'ellenbogen',
        'aussage': 'Der ' + R % 'Tennisarm' + ' entsteht meistens ganz ohne Tennis – durch wiederholte Belastung:',
        'karten': [('greifen', 'Schmerz beim Zugreifen'), ('gewicht', 'Schwache Griffkraft'),
                   ('blitz', 'Druckempfindlich'), ('wiederholung', 'Immer gleiche Bewegung')],
        'unter': 'beim Tennisarm:',
        'punkte': ['Sehne gezielt entlasten', 'Griffkraft aufbauen',
                   'Belastung anpassen', 'Schulter einbeziehen'],
        'band': 'Denn: Die Sehne braucht Belastung – nur in der richtigen Dosis.',
        'frage': 'Schmerzt dein Ellenbogen beim Zugreifen oder Heben?',
    },
    {
        'key': 'Hand', 'page': 'Hand & Handgelenk', 'badge': 'Hand-Edition', 'hero': 'hand',
        'aussage': R % 'Hand und Handgelenk' + ' melden Überlastung leise – aber ziemlich deutlich:',
        'karten': [('kribbeln', 'Kribbelnde Finger'), ('nacht', 'Hand schläft nachts ein'),
                   ('druck', 'Schmerz beim Aufstützen'), ('gewicht', 'Weniger Kraft')],
        'unter': 'bei Hand- und Handgelenksbeschwerden:',
        'punkte': ['Nerv und Sehnen entlasten', 'Beweglichkeit erhalten',
                   'Kraft aufbauen', 'Arbeitsplatz anpassen'],
        'band': 'Denn: Die Hand arbeitet den ganzen Tag – Pausen gehören dazu.',
        'frage': 'Kribbeln deine Finger oder schläft die Hand nachts ein?',
    },
    {
        'key': 'Ferse', 'page': 'Ferse & Fußsohle', 'badge': 'Fersen-Edition', 'hero': 'ferse',
        'aussage': R % 'Fersenschmerz' + ' meldet sich typischerweise bei den ersten Schritten des Tages:',
        'karten': [('zeit', 'Erste Schritte am Morgen'), ('blitz', 'Brennen unter der Ferse'),
                   ('fuss', 'Beschwerden nach Sport'), ('gelenk', 'Steifer Fuß')],
        'unter': 'bei Fersenschmerzen:',
        'punkte': ['Fußsohle dehnen', 'Wade mitbehandeln',
                   'Fußmuskulatur kräftigen', 'Belastung steuern'],
        'band': 'Denn: Die Ferse trägt bei jedem Schritt dein ganzes Gewicht.',
        'frage': 'Schmerzt deine Ferse bei den ersten Schritten am Morgen?',
    },
    {
        'key': 'Reha', 'page': 'Nach der Operation', 'badge': 'Reha-Edition', 'hero': 'reha',
        'eyebrow': 'So begleiten wir dich',
        'aussage': 'Nach einer ' + R % 'Operation' + ' entscheidet die Nachbehandlung mit über das Ergebnis:',
        'karten': [('tropfen', 'Schwellung'), ('gelenk', 'Weniger Beweglichkeit'),
                   ('gewicht', 'Kraftverlust'), ('unsicher', 'Unsicheres Gehen')],
        'unter': 'nach deiner Operation:',
        'punkte': ['Schwellung reduzieren', 'Beweglichkeit aufbauen',
                   'Kraft zurückholen', 'Sicher in den Alltag'],
        'band': 'Denn: Eine gute Nachbehandlung gehört zur Operation dazu.',
        'frage': 'Steht bei dir eine Operation an oder liegt sie hinter dir?',
    },
    {
        'key': 'Lymphe', 'page': 'Schwellung & Lymphe', 'badge': 'Lymph-Edition', 'hero': 'lymphe',
        'aussage': 'Eine ' + R % 'Schwellung' + ' ist kein Schönheitsthema – sie behindert Bewegung:',
        'karten': [('druck', 'Schweregefühl'), ('tropfen', 'Spannungsgefühl'),
                   ('gelenk', 'Weniger Beweglichkeit'), ('zeit', 'Abends schlimmer')],
        'unter': 'bei Schwellungen:',
        'punkte': ['Lymphabfluss anregen', 'Bewegung einbauen',
                   'Kompression begleiten', 'Haut und Gewebe pflegen'],
        'band': 'Denn: Bewegung ist die beste Pumpe für dein Lymphsystem.',
        'frage': 'Fühlen sich Beine oder Arme abends schwer und geschwollen an?',
    },
    {
        'key': 'Schwangerschaft', 'page': 'Schwangerschaft', 'badge': 'Schwangerschafts-Edition',
        'hero': 'schwangerschaft', 'eyebrow': 'Dabei begleiten wir dich',
        'aussage': R % 'Schwangerschaft und Rückbildung' + ' fordern Rumpf und Becken ganz besonders:',
        'karten': [('blitz', 'Rückenschmerzen'), ('gelenk', 'Beckenschmerzen'),
                   ('tropfen', 'Schwere Beine'), ('unsicher', 'Instabiler Rumpf')],
        'unter': 'in Schwangerschaft und Rückbildung:',
        'punkte': ['Beckenboden aktivieren', 'Rumpf stabilisieren',
                   'Haltung entlasten', 'Schrittweise aufbauen'],
        'band': 'Denn: Rückbildung braucht Zeit – und den richtigen Aufbau.',
        'frage': 'Bist du schwanger oder mitten in der Rückbildung?',
    },
    {
        'key': 'Sturzprophylaxe', 'page': 'Sicher auf den Beinen', 'badge': 'Sturzprophylaxe-Edition',
        'hero': 'sturzprophylaxe',
        'aussage': R % 'Sicher auf den Beinen' + ' zu bleiben ist trainierbar – in jedem Alter:',
        'karten': [('nacht', 'Unsicher im Dunkeln'), ('stufen', 'Halt an der Treppe'),
                   ('frage', 'Angst zu stürzen'), ('gewicht', 'Weniger Beinkraft')],
        'unter': 'für mehr Sicherheit im Alltag:',
        'punkte': ['Gleichgewicht trainieren', 'Beinkraft aufbauen',
                   'Gangbild verbessern', 'Sicherheit zurückgewinnen'],
        'band': 'Denn: Kraft und Gleichgewicht lassen sich in jedem Alter aufbauen.',
        'frage': 'Fühlst du dich beim Gehen nicht mehr ganz sicher?',
    },
    {
        'key': 'Knochen', 'page': 'Knochen & Osteoporose', 'badge': 'Knochen-Edition', 'hero': 'knochen',
        'aussage': R % 'Knochen' + ' reagieren auf Belastung – sie brauchen sie sogar, um stark zu bleiben:',
        'karten': [('sitzen', 'Wenig Bewegung'), ('gewicht', 'Weniger Kraft'),
                   ('haltung', 'Rundrücken'), ('unsicher', 'Unsicherer Stand')],
        'unter': 'für stabile Knochen:',
        'punkte': ['Kraft gezielt aufbauen', 'Wirbelsäule aufrichten',
                   'Gleichgewicht schulen', 'Belastung richtig dosieren'],
        'band': 'Denn: Knochen werden stärker, wenn man sie regelmäßig fordert.',
        'frage': 'Willst du deine Knochen gezielt stärken?',
    },
]
