# -*- coding: utf-8 -*-
"""Inhalte der sieben Carousel-Posts. R = rot hervorgehobener Teil der Aussage."""

R = '<span style="color: #8C1010;">%s</span>'

POSTS = [
    {
        'key': 'Ruecken', 'page': 'Rücken', 'badge': 'Rücken-Edition', 'hero': 'ruecken',
        'aussage': 'Bei ' + R % 'Rückenschmerzen' + ' ist Schonung selten die Lösung. Oft steckt dahinter:',
        'karten': [('sitzen', 'Wenig Bewegung'), ('druck', 'Einseitige Belastung'),
                   ('gewicht', 'Schwacher Rumpf'), ('stress', 'Stress &amp; Anspannung')],
        'unter': 'bei Rückenbeschwerden:',
        'punkte': ['Beweglichkeit der Wirbelsäule', 'Rumpfkraft aufbauen',
                   'Belastung dosieren', 'Alltag anpassen'],
        'band': 'Denn: Der Rücken braucht Bewegung – in der richtigen Dosis.',
        'frage': 'Zwickt dein Rücken öfter, als dir lieb ist?',
    },
    {
        'key': 'Knie', 'page': 'Knie', 'badge': 'Knie-Edition', 'hero': 'knie',
        'aussage': R % 'Knieschmerzen' + ' entstehen selten nur im Knie. Häufig spielen mit:',
        'karten': [('gewicht', 'Schwache Hüfte'), ('unsicher', 'Instabile Beinachse'),
                   ('fuss', 'Fußfehlstellung'), ('zeit', 'Zu schnelle Steigerung')],
        'unter': 'bei Knieschmerzen:',
        'punkte': ['Beinachse stabilisieren', 'Hüfte kräftigen',
                   'Kniefunktion prüfen', 'Belastung aufbauen'],
        'band': 'Denn: Ein stabiles Knie beginnt bei Hüfte und Fuß.',
        'frage': 'Schmerzt dein Knie beim Treppensteigen oder Sport?',
    },
    {
        'key': 'Schulter', 'page': 'Schulter', 'badge': 'Schulter-Edition', 'hero': 'schulter',
        'aussage': 'Eine ' + R % 'schmerzhafte Schulter' + ' zeigt sich oft zuerst im Alltag:',
        'karten': [('blitz', 'Schmerz beim Heben'), ('nacht', 'Nachts auf der Seite'),
                   ('gewicht', 'Kraftverlust'), ('gelenk', 'Weniger Beweglichkeit')],
        'unter': 'bei Schulterbeschwerden:',
        'punkte': ['Schulterblatt stabilisieren', 'Rotatorenmanschette stärken',
                   'Beweglichkeit zurückholen', 'Haltung verbessern'],
        'band': 'Denn: Die Schulter arbeitet nur so gut wie ihr Schulterblatt.',
        'frage': 'Schmerzt deine Schulter beim Heben oder nachts?',
    },
    {
        'key': 'Sprunggelenk', 'page': 'Sprunggelenk', 'badge': 'Sprunggelenk-Edition',
        'hero': 'sprunggelenk', 'herobild': 'sprunggelenk-anatomie.jpg',
        'aussage': 'Nach dem ' + R % 'Umknicken' + ' bleibt oft mehr zurück als ein blauer Fleck:',
        'karten': [('unsicher', 'Unsicheres Gefühl'), ('wiederholung', 'Wiederholtes Umknicken'),
                   ('tropfen', 'Restschwellung'), ('gelenk', 'Weniger Beweglichkeit')],
        'unter': 'nach dem Umknicken:',
        'punkte': ['Schwellung reduzieren', 'Beweglichkeit aufbauen',
                   'Gleichgewicht trainieren', 'Zurück in den Sport'],
        'band': 'Denn: Das Band heilt von allein – die Sicherheit im Gelenk nicht.',
        'frage': 'Knickst du öfter um oder fühlt sich dein Fuß unsicher an?',
    },
    {
        'key': 'Buero', 'page': 'Büroalltag', 'badge': 'Büro-Edition', 'hero': 'buero',
        'aussage': R % 'Langes Sitzen' + ' meldet sich selten dort, wo man es erwartet:',
        'karten': [('blitz', 'Nackenverspannung'), ('gelenk', 'Ziehende Schultern'),
                   ('sitzen', 'Steifer Rücken'), ('stress', 'Kopfschmerzen')],
        'unter': 'im Büroalltag:',
        'punkte': ['Arbeitsplatz anpassen', 'Position oft wechseln',
                   'Mobilisieren zwischendurch', 'Rumpf kräftigen'],
        'band': 'Denn: Die beste Haltung ist immer die nächste.',
        'frage': 'Sitzt du den ganzen Tag am Schreibtisch?',
    },
    {
        'key': 'Beckenboden', 'page': 'Beckenboden', 'badge': 'Beckenboden-Edition',
        'hero': 'beckenboden',
        'aussage': 'Der ' + R % 'Beckenboden' + ' arbeitet unbemerkt mit – bis er es nicht mehr tut:',
        'karten': [('tropfen', 'Ungewollter Urinverlust'), ('druck', 'Druckgefühl'),
                   ('blitz', 'Rückenschmerzen'), ('unsicher', 'Unsicherheit im Sport')],
        'unter': 'beim Beckenbodentraining:',
        'punkte': ['Beckenboden wahrnehmen', 'Gezielt aktivieren',
                   'Atmung einbeziehen', 'In den Alltag holen'],
        'band': 'Denn: Beckenbodentraining wirkt – wenn es richtig ausgeführt wird.',
        'frage': 'Willst du deinen Beckenboden gezielt trainieren?',
    },
    {
        'key': 'Sport', 'page': 'Rückkehr in den Sport', 'badge': 'Sport-Edition', 'hero': 'sport',
        'aussage': 'Zurück im ' + R % 'Sport' + ': zu früh gestartet wird schnell zum zweiten Ausfall.',
        'karten': [('zeit', 'Zu früher Start'), ('waage', 'Seitenunterschiede'),
                   ('frage', 'Fehlendes Vertrauen'), ('wiederholung', 'Alte Bewegungsmuster')],
        'unter': 'vor der Rückkehr in den Sport:',
        'punkte': ['Belastbarkeit testen', 'Kraft seitengleich aufbauen',
                   'Sprünge &amp; Richtungswechsel', 'Schrittweise steigern'],
        'band': 'Denn: Schmerzfrei heißt noch nicht belastbar.',
        'frage': 'Willst du nach einer Verletzung sicher zurück in den Sport?',
    },
]
